# Generated by Django 4.0.1 on 2022-01-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_sex_alter_profile_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(default=None),
        ),
    ]
